replicaCount: 4
service:
  type: NodePort
  port: 80

image:
  repository: rafaelgoncalvesmatos/argocd-nodejs
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000